import { Product } from "@/types";

export const products: Product[] = [
  {
    slug: "digestion",
    name: "健脾和胃",
    category: "all",
    price: 128,
    effects: ["消化不良", "软便拉稀", "食欲不振"],
    description: "帮助调理肠胃，改善软便和消化不良。适合换粮期、肠胃敏感的猫狗。",
    suitableFor: "换粮期、肠胃敏感、挑食的猫狗",
    tags: ["肠胃调理", "热销"],
    feedingGuide: { small: "4-6g", medium: "8-14g", large: "16-22g" },
    image: "/products/digestion.png",
  },
  {
    slug: "urinary",
    name: "利尿通淋",
    category: "all",
    price: 128,
    effects: ["尿路问题", "结石体质", "排尿不畅"],
    description: "帮助尿路通畅，减少结晶形成。特别适合有过尿路问题的猫狗日常养护。",
    suitableFor: "有尿路问题史、结石体质的猫狗",
    tags: ["泌尿护理"],
    feedingGuide: { small: "4-6g", medium: "8-14g", large: "16-22g" },
    image: "/products/urinary.png",
  },
  {
    slug: "immunity",
    name: "免疫增强",
    category: "all",
    price: 138,
    effects: ["体质虚弱", "病后恢复", "易生病"],
    description: "帮助提高自身抵抗力，适合体质弱、经常生病或术后恢复期的猫狗。",
    suitableFor: "幼龄/老龄、术后恢复、体质虚弱的猫狗",
    tags: ["免疫力", "热销"],
    feedingGuide: { small: "4-6g", medium: "8-14g", large: "16-22g" },
    image: "/products/immunity.png",
  },
  {
    slug: "skincoat",
    name: "美毛护肤",
    category: "all",
    price: 138,
    effects: ["掉毛严重", "毛枯无光", "皮屑瘙痒"],
    description: "从内滋养毛发和皮肤。帮助减少掉毛，让毛发更有光泽，皮肤更健康。",
    suitableFor: "换毛季、皮肤敏感、毛发差的猫狗",
    tags: ["美毛", "热销"],
    feedingGuide: { small: "4-6g", medium: "8-14g", large: "16-22g" },
    image: "/products/skincoat.png",
  },
  {
    slug: "oral",
    name: "口腔健康",
    category: "all",
    price: 118,
    effects: ["口臭", "牙龈红肿", "牙结石"],
    description: "清新口气，帮助减少牙菌斑和牙结石形成。拌在粮食用，比刷牙省事。",
    suitableFor: "口臭、牙周问题、牙结石的猫狗",
    tags: ["口腔护理", "新品"],
    feedingGuide: { small: "4-6g", medium: "8-14g", large: "16-22g" },
    image: "/products/oral.png",
  },
  {
    slug: "calming",
    name: "安神舒缓",
    category: "all",
    price: 138,
    effects: ["焦虑不安", "分离焦虑", "易惊惧"],
    description: "帮助缓解紧张和焦虑。适用于打雷放炮、独处、外出坐车等容易紧张的场景。",
    suitableFor: "容易焦虑紧张、分离焦虑、雷暴恐惧的猫狗",
    tags: ["情绪安抚"],
    feedingGuide: { small: "4-6g", medium: "8-14g", large: "16-22g" },
    image: "/products/calming.png",
  },
  {
    slug: "teardrop",
    name: "清热去泪痕",
    category: "all",
    price: 118,
    effects: ["泪痕重", "眼分泌物多", "眼周红肿"],
    description: "帮助减少眼泪分泌和泪痕形成。特别适合白色犬猫的泪痕问题。",
    suitableFor: "泪痕重、眼周红褐色印记、眼屎多的猫狗",
    tags: ["泪痕", "新品"],
    feedingGuide: { small: "4-6g", medium: "8-14g", large: "16-22g" },
    image: "/products/teardrop.png",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
